apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
  name: cudainstancetype
spec:
  resources:
    limits:
      cpu: "8"
      nvidia.com/gpu: 1
      memory: "8Gi"
    requests:
      cpu: "500m"
      memory: "1000Mi"
