apiVersion: v1
kind: Service
metadata:
  name: maker-svc
  namespace: minifigures
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: marker
  type: LoadBalancer