apiVersion: v1
kind: PersistentVolume
metadata:
  name: originals-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-pv-data/train-pics"