apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: originals-pvc
  namespace: minifigures
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi