apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-pvc
  namespace: minifigures
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
  volumeMode: Filesystem
